version = 0.1
[default.deploy.parameters]
stack_name = "codextranauts-chatgpt-plugin"
resolve_s3 = true
s3_prefix = "codextranauts-chatgpt-plugin"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
