AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.

Globals:
  Function:
    Timeout: 300

Resources:
  #Lambda
  CodeContextChatGptLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/code_context_chat_gpt_lambda/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
  TeamNamesLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/team_names_lambda/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
