version = 0.1
[default.deploy.parameters]
stack_name = "codextranauts-api"
resolve_s3 = true
s3_prefix = "codextranauts-api"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
