AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: An API Gateway with a custom domain.

Parameters:
  ApiDomain:
    Type: String
    Description: The custom domain name

Globals:
  Function:
    Timeout: 3

Resources:
  # API gateway
  MainApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./api-spec/bundled.yaml

  MainApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: [HelloWorldFunction, ByeWorldFunction]
    Properties:
      RestApiId: !Ref MainApi
      Description: Deployment for Main API

  # MainApiProdStage:
  #   Type: AWS::ApiGateway::Stage
  #   DependsOn: MainApiDeployment
  #   Properties:
  #     StageName: Prod
  #     Description: Production stage
  #     RestApiId: !Ref MainApi
  #     DeploymentId: !Ref MainApiDeployment

  # Lambdas
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId:
              Ref: MainApi
  ByeWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/bye_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        ByeWorld:
          Type: Api
          Properties:
            Path: /bye
            Method: get
            RestApiId:
              Ref: MainApi

  # API mappings
  MainApiBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn:
      - MainApiDeployment
    Properties:
      BasePath: v1
      DomainName: !Ref ApiDomain
      RestApiId: !Ref MainApi
      Stage: Prod
# Outputs:
#   MainApiOutput:
#     Description: "API Gateway endpoint URL for Prod environment"
#     Value: !Sub "https://${MainApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
