AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: An API Gateway with a custom domain.

Parameters:
  ApiDomain:
    Type: String
    Description: The custom domain name

Globals:
  Function:
    Timeout: 3

Resources:
  # API gateway
  MainApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./api-spec/bundled.yaml

  MainApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - CodeContextFunction
      - TeamFunction
    Properties:
      RestApiId: !Ref MainApi
      Description: Deployment for Main API

  # API mappings
  MainApiBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn:
      - MainApiDeployment
    Properties:
      BasePath: v1
      DomainName: !Ref ApiDomain
      RestApiId: !Ref MainApi
      Stage: Prod

  # Lambdas
  CodeContextFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/code_context_chat_gpt_lambda/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /code_context
            Method: get
            RestApiId:
              Ref: MainApi
  TeamFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/team_names_lambda/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        ByeWorld:
          Type: Api
          Properties:
            Path: /team
            Method: get
            RestApiId:
              Ref: MainApi
# Outputs:
#   MainApiOutput:
#     Description: "API Gateway endpoint URL for Prod environment"
#     Value: !Sub "https://${MainApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
