openapi: 3.0.1
info:
  title: Codextranauts API
  description: Main API for Codextranauts ChatGPT plugin
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.bluecollarverse.co.uk/v1/
paths:
  /hello:
    get:
      summary: Retrieve a greeting message
      description: >-
        This endpoint returns a friendly greeting message to the user. No input
        parameters are required.
      operationId: getHello
      tags:
        - greeting
      responses:
        "200":
          description: >-
            Operation was successful. A greeting message is returned in the
            response body.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelloResponse"
              examples:
                example-1:
                  value:
                    message: Hello, World!
        "400":
          description: Bad Request. The request is malformed or invalid.
        "401":
          description: Unauthorized. The request lacks valid authentication credentials.
        "403":
          description: >-
            Forbidden. The server understood the request but refuses to
            authorize it.
        "404":
          description: Not Found. The requested resource could not be found on this server.
        "500":
          description: >-
            Internal Server Error. The server encountered an unexpected
            condition which prevented it from fulfilling the request.
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: aws_proxy
        uri:
          Fn::Sub: >-
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction.Arn}/invocations
  /bye:
    get:
      summary: Retrieve a greeting message
      description: >-
        This endpoint returns a friendly greeting message to the user. No input
        parameters are required.
      operationId: getBye
      tags:
        - greeting
      responses:
        "200":
          description: >-
            Operation was successful. A greeting message is returned in the
            response body.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GoodbyeResponse"
              examples:
                example-1:
                  value:
                    message: Bye, World!
        "400":
          description: Bad Request. The request is malformed or invalid.
        "401":
          description: Unauthorized. The request lacks valid authentication credentials.
        "403":
          description: >-
            Forbidden. The server understood the request but refuses to
            authorize it.
        "404":
          description: Not Found. The requested resource could not be found on this server.
        "500":
          description: >-
            Internal Server Error. The server encountered an unexpected
            condition which prevented it from fulfilling the request.
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: aws_proxy
        uri:
          Fn::Sub: >-
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ByeWorldFunction.Arn}/invocations
components:
  schemas:
    HelloResponse:
      type: object
      properties:
        message:
          type: string
          description: A friendly greeting message. The maximum length is 200 characters.
          example: Hello, World!
          maxLength: 200
      required:
        - message
    GoodbyeResponse:
      type: object
      properties:
        message:
          type: string
          description: A friendly greeting message. The maximum length is 200 characters.
          example: Goodbye, World!
          maxLength: 200
      required:
        - message
