name: SAM build and deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_and_retrieve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install AWS SAM CLI
        run: |
          # Replace these commands with correct installation steps
          curl -L https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip -o aws-sam-cli.zip
          unzip aws-sam-cli.zip -d sam-installation
          sudo ./sam-installation/install

      - name: SAM build and deploy
        working-directory: ./aws
        run: |
          sam build
          sam deploy
