name: Invoke Lambda Function

on:
  push:
  workflow_dispatch:
    inputs:
      url:
        description: Codebase Url
        default: "https://github.com/devmaxime/vectornauts/blob/main/README.md"
        required: true
        type: string

jobs:
  invoke-lambda:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Invoke Lambda Function
        run: |
          aws lambda invoke --function-name CodeVectorizer_1 --payload '${{ inputs.url }}'
