name: Python tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Add project root to PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Aggregate requirements and install dependencies
        run: |
          chmod +x aggregate_requirements.sh
          ./aggregate_requirements.sh

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/all_requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r all_requirements.txt

      - name: Extract stack outputs for lambda ARNs
        run: |
          pip install toml
          echo $(python ./utils/ci/extract_stack_outputs.py) > temp.txt
          echo LLM_LAMBDA_ARN=$(awk '{print $1}' temp.txt) >> $GITHUB_ENV
          echo CODEBASE_VECTORIZER_LAMBDA_ARN=$(awk '{print $2}' temp.txt) >> $GITHUB_ENV
          echo DOC_BUCKET_NAME=$(awk '{print $3}' temp.txt) >> $GITHUB_ENV

      - name: Run unit tests
        env:
          LLM_LAMBDA_ARN: ${{ env.LLM_LAMBDA_ARN }}
          CODEBASE_VECTORIZER_LAMBDA_ARN: ${{ env.CODEBASE_VECTORIZER_LAMBDA_ARN }}
        run: |
          pytest -m unit
