name: Python tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Add project root to PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Extract stack outputs for lambda ARNs
        run: |
          echo $(python ./utils/ci/extract_stack_outputs.py) > temp.txt
          echo LLM_LAMBDA_ARN=$(awk '{print $1}' temp.txt) >> $GITHUB_ENV
          echo CODEBASE_VECTORIZER_LAMBDA_ARN=$(awk '{print $2}' temp.txt) >> $GITHUB_ENV

      - name: Aggregate requirements and install dependencies
        run: |
          chmod +x aggregate_requirements.sh
          ./aggregate_requirements.sh

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/all_requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r all_requirements.txt

      - name: Run unit tests
        run: |
          export LLM_LAMBDA_ARN=${{ env.LLM_LAMBDA_ARN }}
          pytest -m unit
